site_name: Accelerate Science Core AI Concepts
repo_url: https://github.com/acceleratescience/ai-core-concepts/
site_url: https://docs.science.ai.cam.ac.uk/ai-core-concepts/
extra:
  homepage: https://docs.science.ai.cam.ac.uk/
nav:
  - Home: index.md
  - Core Concepts:
    - What is AI?: what-is-ai.md
    - Supervised Learning: supervised-learning.md
    - Unsupervised Learning: unsupervised-learning.md
    - Reinforcement Learning: reinforcement-learning.md
    - Generative AI: generative-ai.md
    - Limitations of AI: limitations-of-ai.md
    - Natural Language Processing: nlp.md
    - Computer Vision: image.md
  - Practical Considerations:
    - The AI Project Lifecycle: ai-project-lifecycle.md
    - Data for AI Models: data.md
    - Training AI Models: training.md
    - Evaluating AI Models: evaluating.md
    - Some Practical Advice: practical.md
    - Next Steps: next-steps.md
theme:
  favicon: imgs/trace.svg
  name: material
  logo: imgs/trace.svg
  features:
    - search.suggest
    - search.highlight
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    annotation: material/chevron-right-circle 
plugins:
  - mkdocstrings
  - search
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
watch:
  - .
